// Real 2026 Lighthouse Half Marathon roster — pulled from Race Roster on 2026-05-28.
// Covers all three races (half / 10K / 5K); each entry carries its `distance`.
// Bib numbers do not collide across the three races, so bib is a unique key.
// Regenerate with lighthouse_half_2026/build_roster.py.

import type { DistanceKey } from "./gpx";

export type LighthouseRacer = {
  bib: number;
  name: string;
  gender: "Male" | "Female" | "Unknown";
  age: number;
  city: string;
  state: string;
  chipTime: string; // "h:mm:ss" (half) or "mm:ss" (5K/10K)
  chipMinutes: number; // numeric for charts
  distance: DistanceKey;
};

export const LIGHTHOUSE_RACERS: LighthouseRacer[] = [
  { bib: 340, name: "Phillip Zavala", gender: "Male", age: 32, city: "LONG BEACH", state: "CA", chipTime: "1:23:49", chipMinutes: 83.8167, distance: "half" },
  { bib: 349, name: "Jorge Hernandez", gender: "Male", age: 25, city: "NORWALK", state: "CA", chipTime: "1:27:34", chipMinutes: 87.5667, distance: "half" },
  { bib: 296, name: "Miguel Peralta", gender: "Male", age: 37, city: "PALMDALE", state: "CA", chipTime: "1:30:07", chipMinutes: 90.1167, distance: "half" },
  { bib: 277, name: "Jason Liang", gender: "Male", age: 25, city: "CORONA", state: "CA", chipTime: "1:32:03", chipMinutes: 92.05, distance: "half" },
  { bib: 339, name: "Kenny Bundy", gender: "Male", age: 45, city: "HOUSTON", state: "TX", chipTime: "1:33:20", chipMinutes: 93.3333, distance: "half" },
  { bib: 359, name: "Brady Karsten", gender: "Male", age: 21, city: "THOUSAND OAKS", state: "CA", chipTime: "1:35:50", chipMinutes: 95.8333, distance: "half" },
  { bib: 265, name: "Julian Rojas", gender: "Male", age: 30, city: "CUDAHY", state: "CA", chipTime: "1:37:59", chipMinutes: 97.9833, distance: "half" },
  { bib: 328, name: "Alex Fukunaga", gender: "Male", age: 27, city: "RANCHO PALOS VERDES", state: "CA", chipTime: "1:39:10", chipMinutes: 99.1667, distance: "half" },
  { bib: 280, name: "Jake Mitchell", gender: "Male", age: 22, city: "RIVERSIDE", state: "CA", chipTime: "1:39:16", chipMinutes: 99.2667, distance: "half" },
  { bib: 383, name: "Victor Claveria", gender: "Male", age: 46, city: "SANTA ANA", state: "CA", chipTime: "1:39:31", chipMinutes: 99.5167, distance: "half" },
  { bib: 352, name: "Ron Du Preez", gender: "Male", age: 74, city: "BANNING", state: "CA", chipTime: "1:45:18", chipMinutes: 105.3, distance: "half" },
  { bib: 291, name: "Eric Jimenez", gender: "Male", age: 26, city: "LAKEWOOD", state: "CA", chipTime: "1:49:49", chipMinutes: 109.817, distance: "half" },
  { bib: 322, name: "Zayne Farah", gender: "Male", age: 22, city: "UPLAND", state: "CA", chipTime: "1:49:59", chipMinutes: 109.983, distance: "half" },
  { bib: 325, name: "Sam Eskandar", gender: "Male", age: 25, city: "FREMONT", state: "CA", chipTime: "1:50:17", chipMinutes: 110.283, distance: "half" },
  { bib: 273, name: "Raymundo Garcia", gender: "Male", age: 49, city: "WESTMINSTER", state: "CA", chipTime: "1:50:31", chipMinutes: 110.517, distance: "half" },
  { bib: 362, name: "Miguel Perez", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "1:50:31", chipMinutes: 110.517, distance: "half" },
  { bib: 365, name: "Matthew Meloni", gender: "Male", age: 22, city: "RIVERSIDE", state: "CA", chipTime: "1:52:00", chipMinutes: 112, distance: "half" },
  { bib: 259, name: "Sergio Valencia", gender: "Male", age: 31, city: "ANAHEIM", state: "CA", chipTime: "1:52:55", chipMinutes: 112.917, distance: "half" },
  { bib: 285, name: "Guadalupe Garcia", gender: "Male", age: 54, city: "CUDAHY", state: "CA", chipTime: "1:53:09", chipMinutes: 113.15, distance: "half" },
  { bib: 348, name: "Grady Roecker", gender: "Male", age: 15, city: "SANTEE", state: "CA", chipTime: "1:53:10", chipMinutes: 113.167, distance: "half" },
  { bib: 338, name: "Vi Chau Tran", gender: "Female", age: 46, city: "HOUSTON", state: "TX", chipTime: "1:53:21", chipMinutes: 113.35, distance: "half" },
  { bib: 368, name: "Erik Ramirez", gender: "Male", age: 40, city: "OCEANSIDE", state: "CA", chipTime: "1:55:10", chipMinutes: 115.167, distance: "half" },
  { bib: 378, name: "Paul Armijo", gender: "Male", age: 39, city: "DOWNEY", state: "CA", chipTime: "1:55:44", chipMinutes: 115.733, distance: "half" },
  { bib: 309, name: "Janssen Chavarria", gender: "Male", age: 45, city: "SOUTH GATE", state: "CA", chipTime: "1:57:02", chipMinutes: 117.033, distance: "half" },
  { bib: 1180, name: "J Villa Murillo", gender: "Male", age: 26, city: "", state: "", chipTime: "1:58:24", chipMinutes: 118.4, distance: "half" },
  { bib: 308, name: "Peter Nguyen", gender: "Male", age: 61, city: "PALOS VERDES ESTATES", state: "CA", chipTime: "1:58:34", chipMinutes: 118.567, distance: "half" },
  { bib: 344, name: "Nina Roecker", gender: "Female", age: 15, city: "SANTEE", state: "CA", chipTime: "1:58:54", chipMinutes: 118.9, distance: "half" },
  { bib: 331, name: "Jennifer Ritter", gender: "Female", age: 41, city: "REDONDO BEACH", state: "CA", chipTime: "1:59:06", chipMinutes: 119.1, distance: "half" },
  { bib: 382, name: "Anayelly Cruz", gender: "Female", age: 17, city: "L.A", state: "CA", chipTime: "1:59:06", chipMinutes: 119.1, distance: "half" },
  { bib: 295, name: "Roni Flores", gender: "Male", age: 44, city: "LANCASTER", state: "CA", chipTime: "1:59:23", chipMinutes: 119.383, distance: "half" },
  { bib: 283, name: "Nancy Barrera", gender: "Female", age: 28, city: "BLOOMINGTON", state: "CA", chipTime: "1:59:38", chipMinutes: 119.633, distance: "half" },
  { bib: 306, name: "Sam Do", gender: "Male", age: 42, city: "SANTA ANA", state: "CA", chipTime: "1:59:59", chipMinutes: 119.983, distance: "half" },
  { bib: 293, name: "Johana Garcia", gender: "Female", age: 45, city: "IRVINE", state: "CA", chipTime: "1:59:59", chipMinutes: 119.983, distance: "half" },
  { bib: 276, name: "Surya Kappa", gender: "Male", age: 43, city: "", state: "", chipTime: "2:00:09", chipMinutes: 120.15, distance: "half" },
  { bib: 350, name: "Andrew Vasquez", gender: "Male", age: 33, city: "MORENO VALLEY", state: "CA", chipTime: "2:00:48", chipMinutes: 120.8, distance: "half" },
  { bib: 392, name: "Sienna Cuellat", gender: "Female", age: 19, city: "", state: "", chipTime: "2:01:51", chipMinutes: 121.85, distance: "half" },
  { bib: 393, name: "Priscilla Huerta", gender: "Female", age: 19, city: "", state: "", chipTime: "2:01:51", chipMinutes: 121.85, distance: "half" },
  { bib: 333, name: "Nicholas Colosi", gender: "Male", age: 25, city: "LA MIRADA", state: "CA", chipTime: "2:01:58", chipMinutes: 121.967, distance: "half" },
  { bib: 292, name: "Aubrey Siverson", gender: "Female", age: 26, city: "TEHACHAPI", state: "CA", chipTime: "2:01:58", chipMinutes: 121.967, distance: "half" },
  { bib: 377, name: "Kassidy Whitmer", gender: "Female", age: 19, city: "", state: "", chipTime: "2:02:21", chipMinutes: 122.35, distance: "half" },
  { bib: 347, name: "Max Potter", gender: "Male", age: 38, city: "LOS ANGELES", state: "CA", chipTime: "2:03:11", chipMinutes: 123.183, distance: "half" },
  { bib: 394, name: "Jesse Aragon", gender: "Male", age: 32, city: "LONG BEACH", state: "CA", chipTime: "2:03:22", chipMinutes: 123.367, distance: "half" },
  { bib: 268, name: "Matt Fitzgerald", gender: "Male", age: 38, city: "", state: "", chipTime: "2:03:45", chipMinutes: 123.75, distance: "half" },
  { bib: 346, name: "Greta Roecker", gender: "Female", age: 45, city: "SANTEE", state: "CA", chipTime: "2:03:48", chipMinutes: 123.8, distance: "half" },
  { bib: 264, name: "Juan Rodriguez", gender: "Male", age: 25, city: "WILMINGTON", state: "CA", chipTime: "2:04:28", chipMinutes: 124.467, distance: "half" },
  { bib: 298, name: "Kyle Brown", gender: "Male", age: 35, city: "", state: "", chipTime: "2:05:13", chipMinutes: 125.217, distance: "half" },
  { bib: 384, name: "Amir Benavides", gender: "Male", age: 33, city: "POMONA", state: "CA", chipTime: "2:07:02", chipMinutes: 127.033, distance: "half" },
  { bib: 263, name: "Rudy Rodriguez", gender: "Male", age: 42, city: "WILMINGTON", state: "CA", chipTime: "2:07:28", chipMinutes: 127.467, distance: "half" },
  { bib: 390, name: "Kevin Contreras", gender: "Male", age: 24, city: "ANAHEIM", state: "CA", chipTime: "2:08:00", chipMinutes: 128, distance: "half" },
  { bib: 253, name: "Lamar Turner", gender: "Male", age: 33, city: "DUARTE", state: "CA", chipTime: "2:08:10", chipMinutes: 128.167, distance: "half" },
  { bib: 399, name: "Remuel Mabutas", gender: "Male", age: 30, city: "WILMINGTON", state: "CA", chipTime: "2:08:37", chipMinutes: 128.617, distance: "half" },
  { bib: 270, name: "Elizabeth Kim", gender: "Female", age: 51, city: "IRVINE", state: "CA", chipTime: "2:09:45", chipMinutes: 129.75, distance: "half" },
  { bib: 278, name: "Kevin Hopp", gender: "Male", age: 55, city: "SAN MARCOS", state: "CA", chipTime: "2:09:45", chipMinutes: 129.75, distance: "half" },
  { bib: 252, name: "Christopher Fukutake", gender: "Male", age: 32, city: "WILMINGTON", state: "CA", chipTime: "2:10:38", chipMinutes: 130.633, distance: "half" },
  { bib: 361, name: "Erick Benicia", gender: "Male", age: 30, city: "TUJUNGA", state: "CA", chipTime: "2:11:41", chipMinutes: 131.683, distance: "half" },
  { bib: 294, name: "Brandon Kavanaugh", gender: "Male", age: 29, city: "ANAHEIM", state: "CA", chipTime: "2:13:43", chipMinutes: 133.717, distance: "half" },
  { bib: 312, name: "Karla Sabido", gender: "Female", age: 26, city: "LANCASTER", state: "CA", chipTime: "2:13:53", chipMinutes: 133.883, distance: "half" },
  { bib: 327, name: "Jennifer Jimenez", gender: "Female", age: 32, city: "NORWALK", state: "CA", chipTime: "2:13:59", chipMinutes: 133.983, distance: "half" },
  { bib: 369, name: "Saira Perez", gender: "Female", age: 35, city: "SANTA ANA", state: "CA", chipTime: "2:15:36", chipMinutes: 135.6, distance: "half" },
  { bib: 275, name: "Jaime Sanchez", gender: "Male", age: 28, city: "DOWNEY", state: "CA", chipTime: "2:16:08", chipMinutes: 136.133, distance: "half" },
  { bib: 354, name: "Jennifer Flynn", gender: "Female", age: 42, city: "", state: "", chipTime: "2:16:40", chipMinutes: 136.667, distance: "half" },
  { bib: 272, name: "Nathan Gorbach", gender: "Male", age: 26, city: "", state: "", chipTime: "2:17:14", chipMinutes: 137.233, distance: "half" },
  { bib: 363, name: "Bianca Lopez", gender: "Female", age: 26, city: "", state: "", chipTime: "2:17:29", chipMinutes: 137.483, distance: "half" },
  { bib: 332, name: "Andrew Rodriguez", gender: "Male", age: 36, city: "BLOOMINGTON", state: "CA", chipTime: "2:17:42", chipMinutes: 137.7, distance: "half" },
  { bib: 266, name: "Jesse Velasco", gender: "Male", age: 36, city: "ALHAMBRA", state: "CA", chipTime: "2:18:21", chipMinutes: 138.35, distance: "half" },
  { bib: 284, name: "Shannon Lewallen", gender: "Female", age: 43, city: "RANCHO PALOS VERDES", state: "CA", chipTime: "2:18:24", chipMinutes: 138.4, distance: "half" },
  { bib: 389, name: "Angela Kao", gender: "Female", age: 38, city: "RANCHO CUCAMONGA", state: "CA", chipTime: "2:18:33", chipMinutes: 138.55, distance: "half" },
  { bib: 304, name: "Nicholas Reta", gender: "Male", age: 30, city: "RICHMOND", state: "TX", chipTime: "2:18:45", chipMinutes: 138.75, distance: "half" },
  { bib: 336, name: "Vanessa Castillo", gender: "Female", age: 30, city: "LONG BEACH", state: "CA", chipTime: "2:19:00", chipMinutes: 139, distance: "half" },
  { bib: 260, name: "Peter Osterc", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "2:19:01", chipMinutes: 139.017, distance: "half" },
  { bib: 366, name: "Andrew Holmquist", gender: "Male", age: 45, city: "", state: "", chipTime: "2:19:07", chipMinutes: 139.117, distance: "half" },
  { bib: 307, name: "Gil Moverman", gender: "Male", age: 56, city: "WOODLAND HILLS", state: "CA", chipTime: "2:19:29", chipMinutes: 139.483, distance: "half" },
  { bib: 311, name: "Andrea Solis", gender: "Female", age: 40, city: "RESEDA", state: "CA", chipTime: "2:19:30", chipMinutes: 139.5, distance: "half" },
  { bib: 341, name: "Luis Sandoval", gender: "Male", age: 36, city: "LOS ANGELES", state: "CA", chipTime: "2:20:28", chipMinutes: 140.467, distance: "half" },
  { bib: 381, name: "Ilana Rozin", gender: "Female", age: 34, city: "LOS ANGELES", state: "CA", chipTime: "2:20:40", chipMinutes: 140.667, distance: "half" },
  { bib: 256, name: "Moises Munoz-Macias", gender: "Male", age: 52, city: "NORWALK", state: "CA", chipTime: "2:20:41", chipMinutes: 140.683, distance: "half" },
  { bib: 400, name: "Sebastian Aguirre", gender: "Male", age: 28, city: "LONG BEACH", state: "CA", chipTime: "2:20:42", chipMinutes: 140.7, distance: "half" },
  { bib: 255, name: "Moises Munoz-Cruz", gender: "Male", age: 28, city: "NORWALK", state: "CA", chipTime: "2:20:44", chipMinutes: 140.733, distance: "half" },
  { bib: 271, name: "Joshua Martin", gender: "Male", age: 19, city: "PINON HILLS", state: "CA", chipTime: "2:21:34", chipMinutes: 141.567, distance: "half" },
  { bib: 300, name: "Conny Quezada", gender: "Female", age: 43, city: "WEST COVINA", state: "CA", chipTime: "2:22:39", chipMinutes: 142.65, distance: "half" },
  { bib: 286, name: "Elaine Villanueva", gender: "Female", age: 29, city: "LOS ANGELES", state: "CA", chipTime: "2:23:00", chipMinutes: 143, distance: "half" },
  { bib: 358, name: "Gracee Weinrieb", gender: "Female", age: 40, city: "", state: "", chipTime: "2:23:55", chipMinutes: 143.917, distance: "half" },
  { bib: 353, name: "Emily Nguyen", gender: "Female", age: 61, city: "PALOS VERDES ESTATES", state: "CA", chipTime: "2:23:56", chipMinutes: 143.933, distance: "half" },
  { bib: 334, name: "Jake Wright", gender: "Male", age: 35, city: "", state: "", chipTime: "2:25:45", chipMinutes: 145.75, distance: "half" },
  { bib: 269, name: "Andrea Aldama", gender: "Female", age: 27, city: "GARDENA", state: "CA", chipTime: "2:28:55", chipMinutes: 148.917, distance: "half" },
  { bib: 301, name: "Tuguldur Zagdsuren", gender: "Male", age: 27, city: "LOS ANGELES", state: "CA", chipTime: "2:29:26", chipMinutes: 149.433, distance: "half" },
  { bib: 356, name: "Patricia Gutierrez", gender: "Female", age: 41, city: "ARLETA", state: "CA", chipTime: "2:30:12", chipMinutes: 150.2, distance: "half" },
  { bib: 335, name: "Job Mendez", gender: "Male", age: 40, city: "BUENA PARK", state: "CA", chipTime: "2:30:13", chipMinutes: 150.217, distance: "half" },
  { bib: 326, name: "Mario Jimenez", gender: "Male", age: 27, city: "LA HABRA", state: "CA", chipTime: "2:31:04", chipMinutes: 151.067, distance: "half" },
  { bib: 251, name: "Roejen Andres", gender: "Male", age: 43, city: "IRVINE", state: "CA", chipTime: "2:33:00", chipMinutes: 153, distance: "half" },
  { bib: 351, name: "Kevin Albarran", gender: "Male", age: 29, city: "WHITTIER", state: "CA", chipTime: "2:36:24", chipMinutes: 156.4, distance: "half" },
  { bib: 364, name: "Yuik Jeon", gender: "Male", age: 52, city: "TORRANCE", state: "CA", chipTime: "2:39:34", chipMinutes: 159.567, distance: "half" },
  { bib: 355, name: "Anthony Ferguson", gender: "Male", age: 42, city: "LOS ANGELES", state: "CA", chipTime: "2:39:35", chipMinutes: 159.583, distance: "half" },
  { bib: 342, name: "Tyler A Womack", gender: "Female", age: 32, city: "SANTA ANA", state: "CA", chipTime: "2:39:35", chipMinutes: 159.583, distance: "half" },
  { bib: 330, name: "Ami Kao", gender: "Female", age: 38, city: "RANCHO CUCAMONGA", state: "CA", chipTime: "2:41:20", chipMinutes: 161.333, distance: "half" },
  { bib: 274, name: "Steven Valentin", gender: "Male", age: 24, city: "LOS ANGELES", state: "CA", chipTime: "2:42:32", chipMinutes: 162.533, distance: "half" },
  { bib: 379, name: "Robert Krikava", gender: "Male", age: 48, city: "NORTHRIDGE", state: "CA", chipTime: "2:42:38", chipMinutes: 162.633, distance: "half" },
  { bib: 337, name: "Mimi Nguyen", gender: "Female", age: 34, city: "", state: "", chipTime: "2:42:51", chipMinutes: 162.85, distance: "half" },
  { bib: 329, name: "Kevin Coleman", gender: "Male", age: 34, city: "", state: "", chipTime: "2:42:51", chipMinutes: 162.85, distance: "half" },
  { bib: 279, name: "Victoria Moran", gender: "Female", age: 55, city: "", state: "", chipTime: "2:44:11", chipMinutes: 164.183, distance: "half" },
  { bib: 391, name: "David Turner Iii", gender: "Male", age: 35, city: "GARDENA", state: "CA", chipTime: "2:45:09", chipMinutes: 165.15, distance: "half" },
  { bib: 367, name: "Ramon Velasquez", gender: "Male", age: 34, city: "", state: "", chipTime: "2:47:04", chipMinutes: 167.067, distance: "half" },
  { bib: 297, name: "Jonathan Bibriesca", gender: "Male", age: 41, city: "", state: "", chipTime: "2:48:18", chipMinutes: 168.3, distance: "half" },
  { bib: 310, name: "Michelle Krok", gender: "Female", age: 1, city: "", state: "", chipTime: "2:49:29", chipMinutes: 169.483, distance: "half" },
  { bib: 289, name: "Samantha Varela", gender: "Female", age: 21, city: "ROWLAND HEIGHTS", state: "CA", chipTime: "2:51:13", chipMinutes: 171.217, distance: "half" },
  { bib: 357, name: "William Tomba", gender: "Male", age: 41, city: "", state: "", chipTime: "2:52:49", chipMinutes: 172.817, distance: "half" },
  { bib: 281, name: "Nicole Velarde", gender: "Female", age: 24, city: "MONTEBELLO", state: "CA", chipTime: "2:55:38", chipMinutes: 175.633, distance: "half" },
  { bib: 303, name: "Raymon Olvera", gender: "Male", age: 23, city: "PACOIMA", state: "CA", chipTime: "2:58:16", chipMinutes: 178.267, distance: "half" },
  { bib: 345, name: "Dawn Klasen", gender: "Female", age: 49, city: "DESERT HOT SPRINGS", state: "CA", chipTime: "2:59:37", chipMinutes: 179.617, distance: "half" },
  { bib: 388, name: "Alex Ferreyra", gender: "Male", age: 38, city: "WESTMINSTER", state: "CA", chipTime: "3:00:51", chipMinutes: 180.85, distance: "half" },
  { bib: 267, name: "Angel Martinez", gender: "Male", age: 58, city: "HAWAIIAN GARDENS", state: "CA", chipTime: "3:06:45", chipMinutes: 186.75, distance: "half" },
  { bib: 287, name: "Wendy Reyes", gender: "Female", age: 47, city: "ROWLAND HEIGHTS", state: "CA", chipTime: "3:07:53", chipMinutes: 187.883, distance: "half" },
  { bib: 317, name: "Darnell Ferrer", gender: "Male", age: 40, city: "LAKEWOOD", state: "CA", chipTime: "3:16:06", chipMinutes: 196.1, distance: "half" },
  { bib: 398, name: "Terri Byrd", gender: "Female", age: 52, city: "SAN JUAN CAPISTRANO", state: "CA", chipTime: "3:30:29", chipMinutes: 210.483, distance: "half" },
  { bib: 396, name: "Heather Sherer", gender: "Female", age: 50, city: "SAN JUAN CAPISTRANO", state: "CA", chipTime: "3:30:29", chipMinutes: 210.483, distance: "half" },
  { bib: 397, name: "Marrin Byrd", gender: "Female", age: 19, city: "SAN JUAN CAPISTRANO", state: "CA", chipTime: "3:30:29", chipMinutes: 210.483, distance: "half" },
  { bib: 254, name: "Jan Yu", gender: "Female", age: 49, city: "HAWTHORNE", state: "CA", chipTime: "3:30:45", chipMinutes: 210.75, distance: "half" },
  { bib: 258, name: "Sergio Rizo", gender: "Male", age: 42, city: "LAWNDALE", state: "CA", chipTime: "3:48:39", chipMinutes: 228.65, distance: "half" },
  { bib: 257, name: "Luz Rizo", gender: "Female", age: 42, city: "LAWNDALE", state: "CA", chipTime: "3:48:41", chipMinutes: 228.683, distance: "half" },
  { bib: 302, name: "Kania John", gender: "Female", age: 28, city: "HUNTINGTON BEACH", state: "CA", chipTime: "4:00:47", chipMinutes: 240.783, distance: "half" },
  { bib: 189, name: "Philip Colunga", gender: "Male", age: 19, city: "SAN BERNARDINO", state: "CA", chipTime: "37:22", chipMinutes: 37.3667, distance: "10k" },
  { bib: 170, name: "Alex Williams", gender: "Male", age: 24, city: "YUCAIPA", state: "CA", chipTime: "42:11", chipMinutes: 42.1833, distance: "10k" },
  { bib: 185, name: "Grzegorz Grabowski", gender: "Male", age: 49, city: "SAN CLEMENTE", state: "CA", chipTime: "46:46", chipMinutes: 46.7667, distance: "10k" },
  { bib: 182, name: "Alex Cruz", gender: "Male", age: 21, city: "RAYMORE", state: "MO", chipTime: "50:38", chipMinutes: 50.6333, distance: "10k" },
  { bib: 166, name: "John Eberts", gender: "Male", age: 67, city: "HUNTINGTON BEACH", state: "CA", chipTime: "51:45", chipMinutes: 51.75, distance: "10k" },
  { bib: 176, name: "Arturo Valencia", gender: "Male", age: 48, city: "POMONA", state: "CA", chipTime: "52:04", chipMinutes: 52.0667, distance: "10k" },
  { bib: 154, name: "Victor Yi", gender: "Male", age: 45, city: "WEST COVINA", state: "CA", chipTime: "52:57", chipMinutes: 52.95, distance: "10k" },
  { bib: 226, name: "Tito Peter", gender: "Male", age: 28, city: "LOS ANGELES", state: "CA", chipTime: "53:54", chipMinutes: 53.9, distance: "10k" },
  { bib: 230, name: "Marco Barriga", gender: "Male", age: 33, city: "", state: "", chipTime: "53:54", chipMinutes: 53.9, distance: "10k" },
  { bib: 160, name: "Raul Cedano", gender: "Male", age: 28, city: "ANAHEIM", state: "CA", chipTime: "53:55", chipMinutes: 53.9167, distance: "10k" },
  { bib: 282, name: "Glen Taylor", gender: "Male", age: 67, city: "", state: "", chipTime: "54:19", chipMinutes: 54.3167, distance: "10k" },
  { bib: 159, name: "Chris Youngblood", gender: "Male", age: 34, city: "LONG BEACH", state: "CA", chipTime: "54:25", chipMinutes: 54.4167, distance: "10k" },
  { bib: 206, name: "Daniel Jacobo", gender: "Male", age: 19, city: "COMPTON", state: "CA", chipTime: "54:32", chipMinutes: 54.5333, distance: "10k" },
  { bib: 194, name: "Javier Arceo", gender: "Male", age: 26, city: "BUENA PARK", state: "CA", chipTime: "54:49", chipMinutes: 54.8167, distance: "10k" },
  { bib: 179, name: "Dick Espinoza", gender: "Male", age: 43, city: "SAN GABRIEL", state: "CA", chipTime: "54:56", chipMinutes: 54.9333, distance: "10k" },
  { bib: 223, name: "Jairo Velazquez", gender: "Male", age: 35, city: "LONG BEACH", state: "CA", chipTime: "55:11", chipMinutes: 55.1833, distance: "10k" },
  { bib: 186, name: "Isaac Mundo", gender: "Male", age: 38, city: "LAKEWOOD", state: "CA", chipTime: "55:28", chipMinutes: 55.4667, distance: "10k" },
  { bib: 196, name: "Ricardo Uriostegui", gender: "Male", age: 27, city: "ANAHEIM", state: "CA", chipTime: "55:37", chipMinutes: 55.6167, distance: "10k" },
  { bib: 193, name: "Isabela Herrera", gender: "Female", age: 27, city: "LONG BEACH", state: "CA", chipTime: "56:01", chipMinutes: 56.0167, distance: "10k" },
  { bib: 153, name: "Gerald Osterkamp", gender: "Male", age: 43, city: "", state: "", chipTime: "56:42", chipMinutes: 56.7, distance: "10k" },
  { bib: 290, name: "Angelica Villarreal", gender: "Female", age: 33, city: "", state: "", chipTime: "57:06", chipMinutes: 57.1, distance: "10k" },
  { bib: 174, name: "Miriam Gamboa", gender: "Female", age: 32, city: "COSTA MESA", state: "CA", chipTime: "57:16", chipMinutes: 57.2667, distance: "10k" },
  { bib: 224, name: "Keven Cardenas", gender: "Male", age: 23, city: "LOS ANGELES", state: "CA", chipTime: "57:41", chipMinutes: 57.6833, distance: "10k" },
  { bib: 180, name: "Axle Martinez", gender: "Male", age: 17, city: "TORRANCE", state: "CA", chipTime: "57:44", chipMinutes: 57.7333, distance: "10k" },
  { bib: 184, name: "Analeece Martinez", gender: "Female", age: 24, city: "LAKEWOOD", state: "CA", chipTime: "57:45", chipMinutes: 57.75, distance: "10k" },
  { bib: 221, name: "Alexis Arias", gender: "Male", age: 22, city: "BALDWIN PARK", state: "CA", chipTime: "58:00", chipMinutes: 58, distance: "10k" },
  { bib: 211, name: "Adam Wypiorczyk", gender: "Male", age: 47, city: "RANCHO SANTA MARGARITA", state: "CA", chipTime: "58:16", chipMinutes: 58.2667, distance: "10k" },
  { bib: 152, name: "Leonardo Oliveira", gender: "Male", age: 51, city: "TORRANCE", state: "CA", chipTime: "58:19", chipMinutes: 58.3167, distance: "10k" },
  { bib: 216, name: "Ilse Lopez", gender: "Female", age: 32, city: "LONG BEACH", state: "CA", chipTime: "58:55", chipMinutes: 58.9167, distance: "10k" },
  { bib: 212, name: "Roan Duarte", gender: "Female", age: 35, city: "CARSON", state: "CA", chipTime: "59:36", chipMinutes: 59.6, distance: "10k" },
  { bib: 220, name: "Ayantu Duguma", gender: "Female", age: 28, city: "RANCHO CUCAMONGA", state: "CA", chipTime: "1:01:11", chipMinutes: 61.1833, distance: "10k" },
  { bib: 208, name: "Paulina Sokolowska", gender: "Female", age: 46, city: "RANCHO SANTA MARGARITA", state: "CA", chipTime: "1:01:50", chipMinutes: 61.8333, distance: "10k" },
  { bib: 168, name: "Logan Quezada", gender: "Male", age: 17, city: "WEST COVINA", state: "CA", chipTime: "1:02:06", chipMinutes: 62.1, distance: "10k" },
  { bib: 204, name: "Alicia Hernandez", gender: "Female", age: 35, city: "LONG BEACH", state: "CA", chipTime: "1:03:19", chipMinutes: 63.3167, distance: "10k" },
  { bib: 202, name: "Laiza Rivera", gender: "Female", age: 26, city: "SANTA FE SPRINGS", state: "CA", chipTime: "1:03:20", chipMinutes: 63.3333, distance: "10k" },
  { bib: 201, name: "Cergio Jacobo", gender: "Male", age: 28, city: "", state: "", chipTime: "1:03:32", chipMinutes: 63.5333, distance: "10k" },
  { bib: 178, name: "Andrew Rubin", gender: "Male", age: 54, city: "SAN DIEGO", state: "CA", chipTime: "1:04:41", chipMinutes: 64.6833, distance: "10k" },
  { bib: 157, name: "Julissa Arias", gender: "Female", age: 28, city: "COMPTON", state: "CA", chipTime: "1:04:46", chipMinutes: 64.7667, distance: "10k" },
  { bib: 219, name: "Jeder Ramos Aguilar", gender: "Female", age: 26, city: "SOUTH GATE", state: "CA", chipTime: "1:05:04", chipMinutes: 65.0667, distance: "10k" },
  { bib: 187, name: "Angie Mancillas", gender: "Female", age: 36, city: "LONG BEACH", state: "CA", chipTime: "1:05:25", chipMinutes: 65.4167, distance: "10k" },
  { bib: 197, name: "Freddy Flores", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "1:05:27", chipMinutes: 65.45, distance: "10k" },
  { bib: 214, name: "Jessica Matias Reyes", gender: "Female", age: 24, city: "LAWNDALE", state: "CA", chipTime: "1:05:49", chipMinutes: 65.8167, distance: "10k" },
  { bib: 181, name: "Elise Marquis", gender: "Female", age: 46, city: "STUDIO CITY", state: "CA", chipTime: "1:06:37", chipMinutes: 66.6167, distance: "10k" },
  { bib: 343, name: "Amy Chambers", gender: "Female", age: 43, city: "LONG BEACH CA", state: "CA", chipTime: "1:07:35", chipMinutes: 67.5833, distance: "10k" },
  { bib: 215, name: "Ziyu Wang", gender: "Male", age: 32, city: "", state: "", chipTime: "1:07:55", chipMinutes: 67.9167, distance: "10k" },
  { bib: 225, name: "Louis Vu", gender: "Male", age: 37, city: "GARDEN GROVE", state: "CA", chipTime: "1:07:58", chipMinutes: 67.9667, distance: "10k" },
  { bib: 191, name: "Christine Maribao", gender: "Female", age: 37, city: "LONG BEACH", state: "CA", chipTime: "1:08:08", chipMinutes: 68.1333, distance: "10k" },
  { bib: 198, name: "Sodanny Pic", gender: "Male", age: 37, city: "LONG BEACH", state: "CA", chipTime: "1:08:08", chipMinutes: 68.1333, distance: "10k" },
  { bib: 162, name: "Brandon Anderson", gender: "Male", age: 37, city: "MURRIETA", state: "CA", chipTime: "1:08:43", chipMinutes: 68.7167, distance: "10k" },
  { bib: 210, name: "Sarah Panitch", gender: "Female", age: 25, city: "PHOENIX", state: "AZ", chipTime: "1:09:15", chipMinutes: 69.25, distance: "10k" },
  { bib: 213, name: "Paul Martinez", gender: "Male", age: 31, city: "WHITTIER", state: "CA", chipTime: "1:09:36", chipMinutes: 69.6, distance: "10k" },
  { bib: 164, name: "Yvette Hernande", gender: "Female", age: 34, city: "LAS VEGAS", state: "NV", chipTime: "1:11:34", chipMinutes: 71.5667, distance: "10k" },
  { bib: 156, name: "Chris Fabia", gender: "Male", age: 46, city: "BUENA PARK", state: "CA", chipTime: "1:12:23", chipMinutes: 72.3833, distance: "10k" },
  { bib: 222, name: "Francisco Gudio", gender: "Male", age: 29, city: "CORONA", state: "CA", chipTime: "1:12:33", chipMinutes: 72.55, distance: "10k" },
  { bib: 175, name: "Guadalupe Aguilar", gender: "Female", age: 60, city: "LOS ANGELES", state: "CA", chipTime: "1:12:39", chipMinutes: 72.65, distance: "10k" },
  { bib: 165, name: "Jesus Hernandez", gender: "Male", age: 62, city: "LOS ANGELES", state: "CA", chipTime: "1:13:33", chipMinutes: 73.55, distance: "10k" },
  { bib: 205, name: "Jill Fabia", gender: "Female", age: 44, city: "BUENA PARK", state: "CA", chipTime: "1:13:42", chipMinutes: 73.7, distance: "10k" },
  { bib: 200, name: "Syreeta Bromfield", gender: "Female", age: 47, city: "LOS ANGELES", state: "CA", chipTime: "1:14:55", chipMinutes: 74.9167, distance: "10k" },
  { bib: 190, name: "Amber Roberts", gender: "Female", age: 34, city: "REDLANDS", state: "CA", chipTime: "1:15:01", chipMinutes: 75.0167, distance: "10k" },
  { bib: 203, name: "Marquisha Wilson", gender: "Female", age: 33, city: "LOS ANGELES", state: "CA", chipTime: "1:16:21", chipMinutes: 76.35, distance: "10k" },
  { bib: 161, name: "Rotana Neth", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "1:17:59", chipMinutes: 77.9833, distance: "10k" },
  { bib: 192, name: "Phil Thach", gender: "Male", age: 39, city: "CORONA", state: "CA", chipTime: "1:18:01", chipMinutes: 78.0167, distance: "10k" },
  { bib: 163, name: "Lizbeth Adame", gender: "Female", age: 35, city: "ANAHEIM", state: "CA", chipTime: "1:19:49", chipMinutes: 79.8167, distance: "10k" },
  { bib: 207, name: "Aranza Servin", gender: "Female", age: 23, city: "PASADENA", state: "CA", chipTime: "1:22:56", chipMinutes: 82.9333, distance: "10k" },
  { bib: 227, name: "Eaisin Alkitbe", gender: "Unknown", age: 39, city: "", state: "", chipTime: "1:23:04", chipMinutes: 83.0667, distance: "10k" },
  { bib: 171, name: "April Justiniani", gender: "Female", age: 41, city: "SANTA CLARITA", state: "CA", chipTime: "1:26:18", chipMinutes: 86.3, distance: "10k" },
  { bib: 188, name: "Jessica Gilliland", gender: "Female", age: 35, city: "TUSTIN", state: "CA", chipTime: "1:26:28", chipMinutes: 86.4667, distance: "10k" },
  { bib: 195, name: "Hannah Bales", gender: "Female", age: 36, city: "FULLERTON", state: "CA", chipTime: "1:26:33", chipMinutes: 86.55, distance: "10k" },
  { bib: 209, name: "Lemuel Lopez", gender: "Male", age: 36, city: "LAKEWOOD", state: "CA", chipTime: "1:27:31", chipMinutes: 87.5167, distance: "10k" },
  { bib: 217, name: "Eman Elpusan", gender: "Female", age: 26, city: "", state: "", chipTime: "1:29:17", chipMinutes: 89.2833, distance: "10k" },
  { bib: 177, name: "Donald Johnson", gender: "Male", age: 31, city: "", state: "", chipTime: "1:30:14", chipMinutes: 90.2333, distance: "10k" },
  { bib: 169, name: "Elizabeth Webb", gender: "Female", age: 39, city: "SAN BERNARDINO", state: "CA", chipTime: "1:35:40", chipMinutes: 95.6667, distance: "10k" },
  { bib: 385, name: "Marisa Rothman", gender: "Female", age: 30, city: "", state: "", chipTime: "1:37:02", chipMinutes: 97.0333, distance: "10k" },
  { bib: 42, name: "Devan Jones", gender: "Male", age: 39, city: "COMPTON", state: "CA", chipTime: "18:14", chipMinutes: 18.2333, distance: "5k" },
  { bib: 107, name: "Jason Tsugawa", gender: "Male", age: 30, city: "", state: "", chipTime: "18:46", chipMinutes: 18.7667, distance: "5k" },
  { bib: 123, name: "Randy Salas", gender: "Male", age: 29, city: "", state: "", chipTime: "20:11", chipMinutes: 20.1833, distance: "5k" },
  { bib: 117, name: "Caroline Iaffaldano", gender: "Female", age: 29, city: "LOS ANGELES", state: "CA", chipTime: "20:50", chipMinutes: 20.8333, distance: "5k" },
  { bib: 3, name: "Zachary Wilkens", gender: "Male", age: 23, city: "NEWPORT BEACH", state: "CA", chipTime: "21:05", chipMinutes: 21.0833, distance: "5k" },
  { bib: 142, name: "Daniel Canela", gender: "Male", age: 12, city: "NORTH HILLS", state: "CA", chipTime: "21:11", chipMinutes: 21.1833, distance: "5k" },
  { bib: 119, name: "Cristian Barry", gender: "Male", age: 25, city: "TORRANCE", state: "CA", chipTime: "22:42", chipMinutes: 22.7, distance: "5k" },
  { bib: 122, name: "Adrian Murguia", gender: "Male", age: 26, city: "INGLEWOOD", state: "CA", chipTime: "23:06", chipMinutes: 23.1, distance: "5k" },
  { bib: 120, name: "Tanner Schafer", gender: "Male", age: 25, city: "TORRANCE", state: "CA", chipTime: "23:18", chipMinutes: 23.3, distance: "5k" },
  { bib: 1189, name: "Francisco Castrejon", gender: "Male", age: 33, city: "COMPTON", state: "CA", chipTime: "23:30", chipMinutes: 23.5, distance: "5k" },
  { bib: 91, name: "Bryan Ventura", gender: "Male", age: 33, city: "CARSON", state: "CA", chipTime: "23:39", chipMinutes: 23.65, distance: "5k" },
  { bib: 58, name: "Vicki Chin", gender: "Female", age: 65, city: "", state: "", chipTime: "23:40", chipMinutes: 23.6667, distance: "5k" },
  { bib: 64, name: "Ivan Gonzalez", gender: "Male", age: 13, city: "LONG BEACH", state: "CA", chipTime: "23:40", chipMinutes: 23.6667, distance: "5k" },
  { bib: 75, name: "Kenzo Landon", gender: "Male", age: 7, city: "PUYALLUP", state: "WA", chipTime: "23:41", chipMinutes: 23.6833, distance: "5k" },
  { bib: 148, name: "Arturo Franco", gender: "Male", age: 46, city: "DOWNEY", state: "CA", chipTime: "23:45", chipMinutes: 23.75, distance: "5k" },
  { bib: 131, name: "Ai Sasaki", gender: "Female", age: 45, city: "PUYALLUP", state: "WA", chipTime: "23:50", chipMinutes: 23.8333, distance: "5k" },
  { bib: 98, name: "Malaika Marigney", gender: "Female", age: 26, city: "LOS ANGELES", state: "CA", chipTime: "24:00", chipMinutes: 24, distance: "5k" },
  { bib: 1, name: "Jocelyn Figueroa", gender: "Female", age: 28, city: "LOS ANGELES", state: "CA", chipTime: "24:04", chipMinutes: 24.0667, distance: "5k" },
  { bib: 67, name: "Dillon Karp", gender: "Male", age: 34, city: "LONG BEACH", state: "CA", chipTime: "24:58", chipMinutes: 24.9667, distance: "5k" },
  { bib: 14, name: "John Medina", gender: "Male", age: 29, city: "BUENA PARK", state: "CA", chipTime: "25:06", chipMinutes: 25.1, distance: "5k" },
  { bib: 50, name: "Bobby Askew", gender: "Male", age: 39, city: "COMPTON", state: "CA", chipTime: "25:10", chipMinutes: 25.1667, distance: "5k" },
  { bib: 73, name: "Noah Aguayo", gender: "Male", age: 11, city: "WHITTIER", state: "CA", chipTime: "25:24", chipMinutes: 25.4, distance: "5k" },
  { bib: 74, name: "Efrain Aguayo", gender: "Male", age: 43, city: "WHITTIER", state: "CA", chipTime: "25:25", chipMinutes: 25.4167, distance: "5k" },
  { bib: 38, name: "Leo Muro", gender: "Male", age: 43, city: "ONTARIO", state: "CA", chipTime: "25:26", chipMinutes: 25.4333, distance: "5k" },
  { bib: 76, name: "Jesse Morales", gender: "Male", age: 32, city: "WHITTIER", state: "CA", chipTime: "25:26", chipMinutes: 25.4333, distance: "5k" },
  { bib: 121, name: "Brian Day", gender: "Male", age: 40, city: "YORBA LINDA", state: "CA", chipTime: "25:26", chipMinutes: 25.4333, distance: "5k" },
  { bib: 106, name: "Monica Martinez", gender: "Female", age: 32, city: "MODESTO", state: "CA", chipTime: "25:38", chipMinutes: 25.6333, distance: "5k" },
  { bib: 56, name: "Lloyd Nelmida", gender: "Male", age: 38, city: "LONG BEACH", state: "CA", chipTime: "26:11", chipMinutes: 26.1833, distance: "5k" },
  { bib: 26, name: "Louis Garcia", gender: "Male", age: 13, city: "JACKSONVILLE", state: "FL", chipTime: "26:12", chipMinutes: 26.2, distance: "5k" },
  { bib: 71, name: "Adrian Sarabia", gender: "Male", age: 33, city: "ANAHEIM", state: "CA", chipTime: "26:15", chipMinutes: 26.25, distance: "5k" },
  { bib: 49, name: "London Nguyen", gender: "Male", age: 10, city: "", state: "", chipTime: "26:30", chipMinutes: 26.5, distance: "5k" },
  { bib: 386, name: "Ruben Verdin", gender: "Male", age: 60, city: "WHITTIER", state: "CA", chipTime: "26:32", chipMinutes: 26.5333, distance: "5k" },
  { bib: 30, name: "Joshua Villanueva", gender: "Male", age: 29, city: "JACKSONVILLE", state: "FL", chipTime: "26:36", chipMinutes: 26.6, distance: "5k" },
  { bib: 125, name: "Emmanuel Barba", gender: "Male", age: 32, city: "COMPTON", state: "CA", chipTime: "26:37", chipMinutes: 26.6167, distance: "5k" },
  { bib: 61, name: "Natalie Goldstone", gender: "Female", age: 25, city: "SANTA ROSA", state: "CA", chipTime: "26:40", chipMinutes: 26.6667, distance: "5k" },
  { bib: 87, name: "Leilani Sanchez", gender: "Female", age: 32, city: "LOS ANGELES", state: "CA", chipTime: "26:44", chipMinutes: 26.7333, distance: "5k" },
  { bib: 1190, name: "Isaac Lopez", gender: "Male", age: 28, city: "PERRIS", state: "CA", chipTime: "26:45", chipMinutes: 26.75, distance: "5k" },
  { bib: 104, name: "Josephann Gerzso", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "26:52", chipMinutes: 26.8667, distance: "5k" },
  { bib: 16, name: "Carlos Pacheco", gender: "Male", age: 48, city: "BUENA PARK", state: "CA", chipTime: "26:56", chipMinutes: 26.9333, distance: "5k" },
  { bib: 48, name: "Mia Kim", gender: "Female", age: 44, city: "", state: "", chipTime: "27:00", chipMinutes: 27, distance: "5k" },
  { bib: 1177, name: "Cruz Leanos", gender: "Male", age: 27, city: "PARAMOUNT", state: "CA", chipTime: "27:08", chipMinutes: 27.1333, distance: "5k" },
  { bib: 139, name: "Boa Park", gender: "Female", age: 40, city: "", state: "", chipTime: "27:10", chipMinutes: 27.1667, distance: "5k" },
  { bib: 15, name: "Daisy Espinoza", gender: "Female", age: 30, city: "BUENA PARK", state: "CA", chipTime: "27:12", chipMinutes: 27.2, distance: "5k" },
  { bib: 138, name: "Taehan Liam Roh", gender: "Male", age: 9, city: "", state: "", chipTime: "27:30", chipMinutes: 27.5, distance: "5k" },
  { bib: 128, name: "Mya Verduzco", gender: "Female", age: 20, city: "LAWNDALE", state: "CA", chipTime: "27:40", chipMinutes: 27.6667, distance: "5k" },
  { bib: 82, name: "Andrew Ulloa", gender: "Male", age: 29, city: "COMPTON", state: "CA", chipTime: "27:44", chipMinutes: 27.7333, distance: "5k" },
  { bib: 102, name: "Jose Salcedo", gender: "Male", age: 44, city: "", state: "", chipTime: "27:56", chipMinutes: 27.9333, distance: "5k" },
  { bib: 144, name: "David Mares", gender: "Male", age: 30, city: "WHITTIER", state: "CA", chipTime: "27:58", chipMinutes: 27.9667, distance: "5k" },
  { bib: 141, name: "Ana Briseno", gender: "Female", age: 33, city: "LONG BEACH", state: "CA", chipTime: "27:59", chipMinutes: 27.9833, distance: "5k" },
  { bib: 46, name: "Eduardo Valenzuela", gender: "Male", age: 30, city: "LONG BEACH", state: "CA", chipTime: "28:31", chipMinutes: 28.5167, distance: "5k" },
  { bib: 90, name: "Ashaley Ventura", gender: "Female", age: 28, city: "CARSON", state: "CA", chipTime: "28:40", chipMinutes: 28.6667, distance: "5k" },
  { bib: 7, name: "Ricardo Frias", gender: "Male", age: 40, city: "BAKERSFIELD", state: "CA", chipTime: "28:47", chipMinutes: 28.7833, distance: "5k" },
  { bib: 59, name: "Yurguen Gonzalez", gender: "Male", age: 30, city: "RIALTO", state: "CA", chipTime: "29:19", chipMinutes: 29.3167, distance: "5k" },
  { bib: 33, name: "Calliope Oliveros", gender: "Female", age: 11, city: "ARLETA", state: "CA", chipTime: "29:27", chipMinutes: 29.45, distance: "5k" },
  { bib: 44, name: "Irish Aguila", gender: "Female", age: 37, city: "LAKEWOOD", state: "CA", chipTime: "29:29", chipMinutes: 29.4833, distance: "5k" },
  { bib: 140, name: "Gustavo Tolentino", gender: "Male", age: 34, city: "SAN FERNANDO", state: "CA", chipTime: "29:30", chipMinutes: 29.5, distance: "5k" },
  { bib: 21, name: "Jonathan Atkinson", gender: "Male", age: 55, city: "LOS ANGELES", state: "CA", chipTime: "29:41", chipMinutes: 29.6833, distance: "5k" },
  { bib: 23, name: "Jeanette Hunsperger", gender: "Female", age: 33, city: "CATHEDRAL CITY", state: "CA", chipTime: "29:45", chipMinutes: 29.75, distance: "5k" },
  { bib: 1196, name: "Cindy Mendez", gender: "Female", age: 29, city: "ORANGE", state: "CA", chipTime: "29:47", chipMinutes: 29.7833, distance: "5k" },
  { bib: 95, name: "Magda Espinoza", gender: "Female", age: 36, city: "LONG BEACH", state: "CA", chipTime: "29:51", chipMinutes: 29.85, distance: "5k" },
  { bib: 150, name: "Christopher Woodward", gender: "Male", age: 56, city: "PHOENIX", state: "AZ", chipTime: "30:10", chipMinutes: 30.1667, distance: "5k" },
  { bib: 57, name: "Peter McIntyre", gender: "Male", age: 60, city: "SANTA ANA", state: "CA", chipTime: "30:18", chipMinutes: 30.3, distance: "5k" },
  { bib: 129, name: "Alexandria Woodley", gender: "Female", age: 28, city: "", state: "", chipTime: "30:38", chipMinutes: 30.6333, distance: "5k" },
  { bib: 1194, name: "Michael Moreno", gender: "Male", age: 16, city: "HAWTHORNE", state: "CA", chipTime: "30:43", chipMinutes: 30.7167, distance: "5k" },
  { bib: 113, name: "Vincent Neang", gender: "Male", age: 25, city: "MONTEBELLO", state: "CA", chipTime: "30:55", chipMinutes: 30.9167, distance: "5k" },
  { bib: 147, name: "Luisa Quintanilla", gender: "Female", age: 45, city: "DOWNEY", state: "CA", chipTime: "31:11", chipMinutes: 31.1833, distance: "5k" },
  { bib: 54, name: "Emanuel Sapiter", gender: "Male", age: 19, city: "DOWNEY", state: "CA", chipTime: "31:12", chipMinutes: 31.2, distance: "5k" },
  { bib: 103, name: "Janet Moreno", gender: "Female", age: 35, city: "LONG BEACH", state: "CA", chipTime: "31:22", chipMinutes: 31.3667, distance: "5k" },
  { bib: 28, name: "Stephanie Bejarano", gender: "Female", age: 35, city: "VAN NUYS", state: "CA", chipTime: "31:22", chipMinutes: 31.3667, distance: "5k" },
  { bib: 17, name: "April Pacheco", gender: "Female", age: 21, city: "BUENA PARK", state: "CA", chipTime: "31:28", chipMinutes: 31.4667, distance: "5k" },
  { bib: 65, name: "Edward Abalos", gender: "Male", age: 53, city: "CARSON", state: "CA", chipTime: "31:29", chipMinutes: 31.4833, distance: "5k" },
  { bib: 36, name: "Ryan Baun", gender: "Male", age: 43, city: "NORTH HOLLYWOOD", state: "CA", chipTime: "31:31", chipMinutes: 31.5167, distance: "5k" },
  { bib: 53, name: "Laura Barrios", gender: "Female", age: 48, city: "DOWNEY", state: "CA", chipTime: "31:32", chipMinutes: 31.5333, distance: "5k" },
  { bib: 114, name: "Vanessa Neang", gender: "Female", age: 29, city: "MONTEBELLO", state: "CA", chipTime: "31:33", chipMinutes: 31.55, distance: "5k" },
  { bib: 40, name: "Michael Forster", gender: "Male", age: 49, city: "GARDEN GROVE", state: "CA", chipTime: "31:44", chipMinutes: 31.7333, distance: "5k" },
  { bib: 78, name: "Yolanda Flores", gender: "Female", age: 51, city: "YORBA LINDA", state: "CA", chipTime: "31:53", chipMinutes: 31.8833, distance: "5k" },
  { bib: 24, name: "Ivan Ramirez", gender: "Male", age: 44, city: "DESERT HOT SPRINGS", state: "CA", chipTime: "32:02", chipMinutes: 32.0333, distance: "5k" },
  { bib: 63, name: "Leanna Cortina", gender: "Female", age: 14, city: "LONG BEACH", state: "CA", chipTime: "32:10", chipMinutes: 32.1667, distance: "5k" },
  { bib: 20, name: "Lorena Bravo", gender: "Female", age: 44, city: "SHERMAN OAKS", state: "CA", chipTime: "32:10", chipMinutes: 32.1667, distance: "5k" },
  { bib: 11, name: "Rachelle Locquiao", gender: "Female", age: 35, city: "LONG BEACH", state: "CA", chipTime: "32:18", chipMinutes: 32.3, distance: "5k" },
  { bib: 34, name: "Lauryn Lawton", gender: "Female", age: 32, city: "SAN BERNARDINO", state: "CA", chipTime: "32:24", chipMinutes: 32.4, distance: "5k" },
  { bib: 85, name: "Michael Wilson", gender: "Male", age: 37, city: "LOS ANGELES", state: "CA", chipTime: "32:28", chipMinutes: 32.4667, distance: "5k" },
  { bib: 149, name: "Krisianna Bock", gender: "Female", age: 49, city: "", state: "", chipTime: "32:45", chipMinutes: 32.75, distance: "5k" },
  { bib: 35, name: "Ronald Elias", gender: "Male", age: 44, city: "NORTH HOLLYWOOD", state: "CA", chipTime: "32:50", chipMinutes: 32.8333, distance: "5k" },
  { bib: 12, name: "Jasmin McGregor", gender: "Female", age: 34, city: "CARSON", state: "CA", chipTime: "32:54", chipMinutes: 32.9, distance: "5k" },
  { bib: 55, name: "Joseph Alonzo", gender: "Male", age: 34, city: "SIGNAL HILL", state: "CA", chipTime: "33:01", chipMinutes: 33.0167, distance: "5k" },
  { bib: 72, name: "Talena Williamson", gender: "Female", age: 38, city: "NEWBURY PARK", state: "CA", chipTime: "33:06", chipMinutes: 33.1, distance: "5k" },
  { bib: 13, name: "Joseph McGregor", gender: "Male", age: 35, city: "CARSON", state: "CA", chipTime: "33:17", chipMinutes: 33.2833, distance: "5k" },
  { bib: 105, name: "Sarahi Ramirez", gender: "Female", age: 22, city: "BUENA PARK", state: "CA", chipTime: "33:17", chipMinutes: 33.2833, distance: "5k" },
  { bib: 81, name: "Austin Williams", gender: "Male", age: 27, city: "ANAHEIM", state: "CA", chipTime: "33:49", chipMinutes: 33.8167, distance: "5k" },
  { bib: 52, name: "Michelle Smith", gender: "Female", age: 35, city: "CALIMESA", state: "CA", chipTime: "34:04", chipMinutes: 34.0667, distance: "5k" },
  { bib: 118, name: "Candy Pelaez", gender: "Female", age: 26, city: "LOS ANGELES", state: "CA", chipTime: "34:12", chipMinutes: 34.2, distance: "5k" },
  { bib: 112, name: "Jimmy Wang", gender: "Male", age: 30, city: "MONTEBELLO", state: "CA", chipTime: "34:22", chipMinutes: 34.3667, distance: "5k" },
  { bib: 110, name: "Jonathan Licud", gender: "Male", age: 43, city: "MURRIETA", state: "CA", chipTime: "34:23", chipMinutes: 34.3833, distance: "5k" },
  { bib: 109, name: "Janice Licud", gender: "Female", age: 43, city: "MURRIETA", state: "CA", chipTime: "34:23", chipMinutes: 34.3833, distance: "5k" },
  { bib: 27, name: "Shilla Patel", gender: "Female", age: 58, city: "LONG BEACH", state: "CA", chipTime: "35:20", chipMinutes: 35.3333, distance: "5k" },
  { bib: 115, name: "Nira Tea", gender: "Female", age: 57, city: "MONTEBELLO", state: "CA", chipTime: "35:21", chipMinutes: 35.35, distance: "5k" },
  { bib: 80, name: "Jenay Marcotte", gender: "Male", age: 41, city: "MURRIETA", state: "CA", chipTime: "35:21", chipMinutes: 35.35, distance: "5k" },
  { bib: 79, name: "Jenay Marcotte", gender: "Female", age: 47, city: "MURRIETA", state: "CA", chipTime: "35:22", chipMinutes: 35.3667, distance: "5k" },
  { bib: 39, name: "Jose Estrella", gender: "Male", age: 41, city: "FONTANA", state: "CA", chipTime: "35:27", chipMinutes: 35.45, distance: "5k" },
  { bib: 86, name: "Albert Matas", gender: "Male", age: 59, city: "LA PUENTE", state: "CA", chipTime: "35:43", chipMinutes: 35.7167, distance: "5k" },
  { bib: 93, name: "Irlanda Ibarra", gender: "Female", age: 24, city: "LONG BEACH", state: "CA", chipTime: "35:47", chipMinutes: 35.7833, distance: "5k" },
  { bib: 143, name: "Alicia Herrera", gender: "Female", age: 33, city: "LONG BEACH", state: "CA", chipTime: "35:51", chipMinutes: 35.85, distance: "5k" },
  { bib: 43, name: "Saranyan Uthayakumar", gender: "Male", age: 25, city: "LAKE FOREST", state: "CA", chipTime: "35:52", chipMinutes: 35.8667, distance: "5k" },
  { bib: 96, name: "Lulu Murillo", gender: "Female", age: 35, city: "LYNWOOD", state: "CA", chipTime: "36:00", chipMinutes: 36, distance: "5k" },
  { bib: 94, name: "Esmeralda Cardenas", gender: "Female", age: 24, city: "LONG BEACH", state: "CA", chipTime: "36:04", chipMinutes: 36.0667, distance: "5k" },
  { bib: 89, name: "Edith Gonzalez", gender: "Female", age: 31, city: "SIGNAL HILL", state: "CA", chipTime: "36:05", chipMinutes: 36.0833, distance: "5k" },
  { bib: 18, name: "Rylee Marr", gender: "Female", age: 25, city: "LONG BEACH", state: "CA", chipTime: "36:18", chipMinutes: 36.3, distance: "5k" },
  { bib: 1176, name: "Jasmine Elkess", gender: "Female", age: 27, city: "ALHAMBRA", state: "CA", chipTime: "36:51", chipMinutes: 36.85, distance: "5k" },
  { bib: 108, name: "Marco Murillo", gender: "Male", age: 22, city: "BUENA PARK", state: "CA", chipTime: "36:54", chipMinutes: 36.9, distance: "5k" },
  { bib: 77, name: "Karmen Donnally", gender: "Female", age: 49, city: "YORBA LINDA", state: "CA", chipTime: "36:59", chipMinutes: 36.9833, distance: "5k" },
  { bib: 1193, name: "Ibedarai Morena", gender: "Female", age: 29, city: "", state: "", chipTime: "37:00", chipMinutes: 37, distance: "5k" },
  { bib: 88, name: "Taylor Ciano", gender: "Female", age: 30, city: "REDONDO BEACH", state: "CA", chipTime: "37:14", chipMinutes: 37.2333, distance: "5k" },
  { bib: 111, name: "Simone Williams", gender: "Female", age: 36, city: "LOS ANGELES", state: "CA", chipTime: "37:15", chipMinutes: 37.25, distance: "5k" },
  { bib: 31, name: "Adriana Justiniani", gender: "Female", age: 12, city: "SANTA CLARITA", state: "CA", chipTime: "37:16", chipMinutes: 37.2667, distance: "5k" },
  { bib: 1195, name: "Lori White", gender: "Female", age: 49, city: "ANAHEIM", state: "CA", chipTime: "37:23", chipMinutes: 37.3833, distance: "5k" },
  { bib: 9, name: "Angie Candido", gender: "Female", age: 29, city: "", state: "", chipTime: "37:38", chipMinutes: 37.6333, distance: "5k" },
  { bib: 84, name: "Alyssa Diaz", gender: "Female", age: 31, city: "LA PUENTE", state: "CA", chipTime: "37:44", chipMinutes: 37.7333, distance: "5k" },
  { bib: 136, name: "Vivian Rodriguez", gender: "Female", age: 37, city: "MONTCLAIR", state: "CA", chipTime: "37:50", chipMinutes: 37.8333, distance: "5k" },
  { bib: 135, name: "Robert Bankston", gender: "Male", age: 44, city: "WHITTIER", state: "CA", chipTime: "38:01", chipMinutes: 38.0167, distance: "5k" },
  { bib: 83, name: "Robert Callanan", gender: "Male", age: 34, city: "CARSON", state: "CA", chipTime: "38:40", chipMinutes: 38.6667, distance: "5k" },
  { bib: 97, name: "Erik Esquivel", gender: "Male", age: 39, city: "WILMINGTON", state: "CA", chipTime: "38:43", chipMinutes: 38.7167, distance: "5k" },
  { bib: 127, name: "Beth Nicart", gender: "Female", age: 55, city: "LONG BEACH", state: "CA", chipTime: "39:16", chipMinutes: 39.2667, distance: "5k" },
  { bib: 116, name: "Ralph Roldan", gender: "Male", age: 61, city: "MONTEBELLO", state: "CA", chipTime: "39:48", chipMinutes: 39.8, distance: "5k" },
  { bib: 1178, name: "Leonardo Bermudez", gender: "Male", age: 34, city: "COMPTON", state: "CA", chipTime: "39:53", chipMinutes: 39.8833, distance: "5k" },
  { bib: 62, name: "Brisel Cortina", gender: "Female", age: 9, city: "LONG BEACH", state: "CA", chipTime: "40:18", chipMinutes: 40.3, distance: "5k" },
  { bib: 60, name: "Leonardo Cortina", gender: "Male", age: 36, city: "LONG BEACH", state: "CA", chipTime: "40:18", chipMinutes: 40.3, distance: "5k" },
  { bib: 2, name: "Nicole Fisher", gender: "Female", age: 30, city: "GARDEN GROVE", state: "CA", chipTime: "40:38", chipMinutes: 40.6333, distance: "5k" },
  { bib: 29, name: "Brittany Lara", gender: "Female", age: 12, city: "INGLEWOOD", state: "CA", chipTime: "40:42", chipMinutes: 40.7, distance: "5k" },
  { bib: 37, name: "Ricardo Lara", gender: "Male", age: 33, city: "INGLEWOOD", state: "CA", chipTime: "40:42", chipMinutes: 40.7, distance: "5k" },
  { bib: 32, name: "William Oliveros", gender: "Male", age: 41, city: "ARLETA", state: "CA", chipTime: "40:45", chipMinutes: 40.75, distance: "5k" },
  { bib: 70, name: "Angel Salinas", gender: "Male", age: 33, city: "WHITTIER", state: "CA", chipTime: "40:46", chipMinutes: 40.7667, distance: "5k" },
  { bib: 134, name: "Ryan Shin", gender: "Male", age: 9, city: "", state: "", chipTime: "41:00", chipMinutes: 41, distance: "5k" },
  { bib: 132, name: "Eric Shim", gender: "Male", age: 42, city: "", state: "", chipTime: "41:01", chipMinutes: 41.0167, distance: "5k" },
  { bib: 133, name: "Jiwon Pack", gender: "Female", age: 42, city: "", state: "", chipTime: "41:09", chipMinutes: 41.15, distance: "5k" },
  { bib: 145, name: "Jordon Navarro", gender: "Male", age: 34, city: "LONG BEACH", state: "CA", chipTime: "41:10", chipMinutes: 41.1667, distance: "5k" },
  { bib: 47, name: "Mike Nguyen", gender: "Male", age: 54, city: "", state: "", chipTime: "41:32", chipMinutes: 41.5333, distance: "5k" },
  { bib: 25, name: "Isabel Escobar", gender: "Female", age: 28, city: "GARDENA", state: "CA", chipTime: "41:33", chipMinutes: 41.55, distance: "5k" },
  { bib: 22, name: "Jesse Carrasco", gender: "Male", age: 61, city: "LAKEWOOD", state: "CA", chipTime: "43:00", chipMinutes: 43, distance: "5k" },
  { bib: 1175, name: "Marina Elkess", gender: "Female", age: 27, city: "ALHAMBRA", state: "CA", chipTime: "43:24", chipMinutes: 43.4, distance: "5k" },
  { bib: 1174, name: "Darlene Mejia", gender: "Female", age: 26, city: "LONG BEACH", state: "CA", chipTime: "43:33", chipMinutes: 43.55, distance: "5k" },
  { bib: 6, name: "Paola Andrade", gender: "Female", age: 21, city: "LAWNDALE", state: "CA", chipTime: "44:27", chipMinutes: 44.45, distance: "5k" },
  { bib: 1192, name: "Adrian Medina", gender: "Male", age: 28, city: "HAWTHORNE", state: "CA", chipTime: "44:53", chipMinutes: 44.8833, distance: "5k" },
  { bib: 5, name: "Itzel Sayas", gender: "Female", age: 24, city: "LAWNDALE", state: "CA", chipTime: "44:54", chipMinutes: 44.9, distance: "5k" },
  { bib: 1191, name: "Jovhana Moreno", gender: "Female", age: 27, city: "HAWTHORNE", state: "CA", chipTime: "44:57", chipMinutes: 44.95, distance: "5k" },
  { bib: 126, name: "Jose Jeronimo", gender: "Male", age: 32, city: "COMPTON", state: "CA", chipTime: "45:07", chipMinutes: 45.1167, distance: "5k" },
  { bib: 146, name: "Cynthia Vidrio", gender: "Female", age: 33, city: "LONG BEACH", state: "CA", chipTime: "45:34", chipMinutes: 45.5667, distance: "5k" },
  { bib: 66, name: "Gabriela Franco", gender: "Female", age: 51, city: "HESPERIA", state: "CA", chipTime: "46:38", chipMinutes: 46.6333, distance: "5k" },
  { bib: 1179, name: "Alex Cruz", gender: "Male", age: 37, city: "", state: "", chipTime: "50:00", chipMinutes: 50, distance: "5k" },
  { bib: 51, name: "Krystal Mendoza", gender: "Female", age: 27, city: "", state: "", chipTime: "50:16", chipMinutes: 50.2667, distance: "5k" },
  { bib: 124, name: "Cynthia Phan", gender: "Female", age: 28, city: "HUNTINGTON BEACH", state: "CA", chipTime: "52:37", chipMinutes: 52.6167, distance: "5k" },
  { bib: 68, name: "Emily Camacho", gender: "Female", age: 28, city: "HAWTHORNE", state: "CA", chipTime: "52:37", chipMinutes: 52.6167, distance: "5k" },
  { bib: 130, name: "Kimberly Bella Dao", gender: "Female", age: 27, city: "NEWPORT BEACH", state: "CA", chipTime: "52:39", chipMinutes: 52.65, distance: "5k" },
  { bib: 137, name: "Pillijong Roh", gender: "Male", age: 38, city: "", state: "", chipTime: "52:57", chipMinutes: 52.95, distance: "5k" },
  { bib: 167, name: "Jessica Frankel", gender: "Female", age: 26, city: "", state: "", chipTime: "55:09", chipMinutes: 55.15, distance: "5k" },
  { bib: 183, name: "Dilpreet Gill", gender: "Female", age: 28, city: "RANCHO CUCAMONGA", state: "CA", chipTime: "58:28", chipMinutes: 58.4667, distance: "5k" },
  { bib: 45, name: "Nana Sarkodee-Adoo", gender: "Female", age: 30, city: "LONG BEACH", state: "CA", chipTime: "59:30", chipMinutes: 59.5, distance: "5k" },
  { bib: 41, name: "Eva Levingston", gender: "Female", age: 31, city: "LONG BEACH", state: "CA", chipTime: "59:31", chipMinutes: 59.5167, distance: "5k" },
  { bib: 92, name: "Sunny Chow", gender: "Female", age: 67, city: "RANCHO CUCAMONGA", state: "CA", chipTime: "1:01:22", chipMinutes: 61.3667, distance: "5k" },
  { bib: 158, name: "Harmony Wren", gender: "Female", age: 31, city: "", state: "", chipTime: "1:02:28", chipMinutes: 62.4667, distance: "5k" },
  { bib: 173, name: "Alexandra Rae", gender: "Female", age: 24, city: "", state: "", chipTime: "1:08:26", chipMinutes: 68.4333, distance: "5k" },
  { bib: 172, name: "Makayla Mercado", gender: "Female", age: 22, city: "", state: "", chipTime: "1:08:35", chipMinutes: 68.5833, distance: "5k" },
  { bib: 1199, name: "Jessica Gonzalez", gender: "Female", age: 35, city: "LONG BEACH", state: "CA", chipTime: "1:08:36", chipMinutes: 68.6, distance: "5k" },
];

/** Lookup a racer by bib number. Returns undefined if no match. */
export function racerByBib(bib: number | string): LighthouseRacer | undefined {
  const n = typeof bib === "string" ? parseInt(bib, 10) : bib;
  if (!Number.isFinite(n)) return undefined;
  return LIGHTHOUSE_RACERS.find((r) => r.bib === n);
}
