/**
 * Loads pre-built run data from runs.json (generated by build-runs.mjs).
 * Staggers progress callbacks to keep the loading screen animation visible.
 */

import type { Run, RunsData } from "./types";

const BASE = "/downtownkruz";

export interface LoadProgress {
  total: number;
  loaded: number;
  name: string;
  date: string;
}

function formatDate(iso: string | null): string {
  if (!iso) return "";
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function loadRunsProgressive(
  onProgress: (progress: LoadProgress) => void,
  signal?: AbortSignal
): Promise<Run[]> {
  const res = await fetch(`${BASE}/runs.json`, { signal });
  if (!res.ok) throw new Error(`Failed to fetch runs.json: ${res.status}`);
  const data: RunsData = await res.json();

  const total = data.runs.length;
  const runs: Run[] = [];

  for (let i = 0; i < data.runs.length; i++) {
    if (signal?.aborted) throw new DOMException("Aborted", "AbortError");

    const raw = data.runs[i];
    const run: Run = {
      id: raw.id,
      name: raw.name,
      startTime: raw.startTime,
      endTime: raw.endTime,
      distanceKm: raw.distanceKm,
      points: raw.points.map(([lat, lon]) => ({ lat, lon })),
    };

    runs.push(run);
    onProgress({
      total,
      loaded: i + 1,
      name: raw.name,
      date: formatDate(raw.startTime),
    });

    // Stagger entries so the loading screen animates visibly
    await delay(40);
  }

  return runs;
}
