/*
 * ....................NNN..NNN................................
 * ....................NNN..NNN................................
 * .........................NNN............. ..................
 * .NNNNNNNNNNNNNNNN...NNN..NNN..NNNN.. NNNNNNNNNN..NNN........
 * .NNN ..ZNNN,...NNN .NNN..NNN.NNN:...NNN .. NNNN. NNN........
 * .NNM....NNN....NNN..NNN..NNNNNN....NNN......NNN.............
 * .NNN....NNN....NNN..NNN..NNNNNNN...NNN......NNN.............
 * .NNN....NNN....NNN..NNN..NNN..NNN ..NNN .. NNNN.............
 * .NNN....NNN....NNN..NNN..NNN...NNN..ONNNNNNNNNN..NNN........
 * .NNN....NNN....NNN..MNN..NNN....NNN7...NNN .NND. NNM........
 * ............................................................
 * NNNNNN. NNN..NNDDNNNN 8NNNNN... NNN .NN=NNNNN......NNNNN.NNN
 * NNNNNN..NNN..NNNNDNNNNNNNNNNN,. NNN..NNNNNMNNN...NNNNNNNNNNN
 * .NNN....NNN..NNN....NNN.. .NNN. NNN..NND....NNN.MNN ....MNNN
 * .NNN....NNN..NNN....NNN....NNN. NNN..NNN....NNN.NNN......NNN
 * .NNN....NNN..NNN....NNN....NNN. NNN..NNN....NNN.NNN ....DNNN
 * .NNNNN..NNN..NNN....NNN....NNN. NNN..NNN....NNN..NNNN .NNNNN
 * ..NNNN..NNN..NNN....NNN....NNN. NNN..NNN....NNN...MNNNNN8NNN
 * .........................................................NN.
 * ................................................?NNN  . NNN.
 * .................................................+NNNNNNNN..
 * .....................................................NN.....
 * @package    Mika
 * @author     Mika Timing GmbH <info@mikatiming.de>
 * @copyright  2026 Mika Timing GmbH
 */
define("Mika/SearchProvider",[],function(){return function(n){return{search:function(e){var r=new jQuery.Deferred,t=[],t="function"==typeof n.url[n.mode].parameters?n.url[n.mode].parameters():n.url[n.mode].parameters,t=jQuery.extend(!0,{},t,{options:{string:e,pid:n.pid,event:n.event_id,highlight_events:n.highlight_events}});return jQuery.ajax({url:n.url[n.mode].base,type:"POST",data:t,success:function(e){r.resolve(e)}}),r.promise()}}}});