/**
 * Zero-secret local dev stack.
 *
 *   node scripts/dev-local.mjs
 *
 * Gets a laptop from a fresh clone to a browsable dev server without any
 * production credentials: writes a .env.local pointed at a local Postgres,
 * pushes the schema, seeds the event + the 100-rower September demo board,
 * then tells you to run `npm run dev`.
 *
 * What works after this: /row100k and its board, stats, profiles and log form,
 * plus every page that doesn't reach a cloud service. What doesn't: photo
 * pages (Cloudflare R2), face rec (AWS Rekognition), receipts (Resend), the
 * buy flow (PayPal) and Google sign-in — those need real keys, which live in
 * Vercel (`npx vercel env pull .env.local`). See .env.example.
 *
 * Never overwrites an existing .env.local.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { connect } from "node:net";

const LOCAL_DB = "postgresql://postgres:postgres@localhost:5432/mikian?schema=public";

const say = (m) => console.log(m);
const die = (m) => {
  console.error(`\n✖ ${m}\n`);
  process.exit(1);
};

/* ── 1. .env.local ───────────────────────────────────────────────────────── */
if (existsSync(".env.local")) {
  say("· .env.local exists — leaving it alone");
} else {
  writeFileSync(
    ".env.local",
    [
      "# Generated by scripts/dev-local.mjs — local sandbox, no real credentials.",
      "# For the real values: npx vercel env pull .env.local   (see .env.example)",
      `POSTGRES_URL=${LOCAL_DB}`,
      `POSTGRES_URL_NON_POOLING=${LOCAL_DB}`,
      `DATABASE_URL=${LOCAL_DB}`,
      "NEXTAUTH_URL=http://localhost:3000",
      "NEXT_PUBLIC_BASE_URL=http://localhost:3000",
      `NEXTAUTH_SECRET=${randomBytes(32).toString("base64")}`,
      "# Payments lock only on the exact string \"true\".",
      "PAYMENTS_LOCKED=true",
      "PAYPAL_ENV=sandbox",
      "",
    ].join("\n"),
  );
  say("✓ wrote .env.local (local Postgres, no secrets)");
}

/* ── 2. is Postgres up? ──────────────────────────────────────────────────── */
const url = (readFileSync(".env.local", "utf8").match(/^POSTGRES_URL=(.+)$/m) || [])[1]?.trim();
if (!url) die("POSTGRES_URL is missing from .env.local");

let host = "localhost";
let port = 5432;
try {
  const u = new URL(url);
  host = u.hostname || host;
  port = Number(u.port) || port;
} catch {
  die(`POSTGRES_URL doesn't parse as a URL: ${url}`);
}

const reachable = await new Promise((resolve) => {
  const sock = connect({ host, port });
  const done = (ok) => {
    sock.destroy();
    resolve(ok);
  };
  sock.setTimeout(3000);
  sock.once("connect", () => done(true));
  sock.once("timeout", () => done(false));
  sock.once("error", () => done(false));
});

if (!reachable) {
  die(
    `No Postgres answering at ${host}:${port}.\n\n` +
      "  Docker (any OS):  docker run -d --name mikian-pg -p 5432:5432 \\\n" +
      "                      -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=mikian postgres:16\n" +
      "  macOS:            brew install postgresql@16 && brew services start postgresql@16\n" +
      "  Windows:          install Postgres 16, then create a `mikian` database\n\n" +
      "  Then re-run: node scripts/dev-local.mjs\n" +
      "  (Already have a database elsewhere? Point POSTGRES_URL at it instead.)",
  );
}
say(`✓ Postgres reachable at ${host}:${port}`);

/* ── 3. schema + seeds ───────────────────────────────────────────────────── */
const run = (label, cmd) => {
  say(`\n▸ ${label}`);
  const r = spawnSync(cmd, { stdio: "inherit", shell: true });
  if (r.status !== 0) die(`${label} failed — see the output above.`);
};

run("prisma db push", "npm run prisma:push");
run("seed: event + photographers", "npm run prisma:seed");
run("seed: 100-rower demo board", "npm run row100k:demo");

say(
  [
    "",
    "─────────────────────────────────────────────",
    "Ready. Start the server:",
    "",
    "  npm run dev",
    "",
    "Then open  http://localhost:3000/row100k",
    "(dev runs in demo mode: the seeded board, clock pinned to Sep 20)",
    "─────────────────────────────────────────────",
  ].join("\n"),
);
